# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true
    CoreBundle\Service\:
      resource: '../../src/CoreBundle/Service/*'
      exclude: '../../src/CoreBundle/Service/{ShareService.php, Storage/*}'
    CoreBundle\Service\Storage\LocalFilesystemShareStorage:
      arguments:
        - "%local_storage_location%"
    CoreBundle\Service\ShareService:
      arguments:
        - "@doctrine.orm.entity_manager"
        - "@CoreBundle\\Service\\Storage\\LocalFilesystemShareStorage"
    FrontendBundle\Controller\:
      resource: '../../src/FrontendBundle/Controller/*'
      public: true
      tags: ['controller.service_arguments']
